name: Compile Checks

on:
  push:

jobs:
  compile-checks:
    name: Check project compiles
    strategy:
      matrix:
        preset:
          - nucleo-debug
          - nucleo-release
          - nucleo-relwithdebinfo
          - nucleo-debug-eth
          - nucleo-release-eth
          - nucleo-relwithdebinfo-eth
          - board-debug
          - board-release
          - board-relwithdebinfo
          - board-debug-eth
          - board-release-eth
          - board-relwithdebinfo-eth
          - simulator
      fail-fast: false
    uses: ./.github/workflows/build.yml
    with:
      preset: ${{ matrix.preset }}
